# Generated by Django 3.2.9 on 2021-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211220_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
