# Generated by Django 3.2.9 on 2021-12-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator',
            new_name='avatar',
        ),
    ]
